# Config file

file_format: ".nii.gz" #".b2nd" for nnUNet_preprocessed
excluded_strings: "_seg.b2nd"
sam1_checkpoint: "/path/to/sam/sam_vit_h_4b8939.pth"
sam2_checkpoint: "/path/to/sam2/sam2.1_hiera_large.pt"
masks_per_image: 20 # n
